# Generated by Django 5.1.8 on 2025-04-10 17:55

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='First Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone Number')),
                ('msg', models.TextField(max_length=5000, verbose_name='Message')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('email', models.EmailField(max_length=255, verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Phone Number')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading', wagtail.fields.RichTextField(max_length=255, verbose_name='Heading')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('mission_heading', wagtail.fields.RichTextField(max_length=255, verbose_name='Heading')),
                ('mission_description', models.TextField(max_length=2000, verbose_name='Description')),
                ('since_experience', models.PositiveSmallIntegerField(default=0, verbose_name='Since Experience')),
                ('evolution_heading', wagtail.fields.RichTextField(max_length=255, verbose_name='Heading')),
                ('evolution_points', wagtail.fields.StreamField([('point', 2)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 25, 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'max_length': 2000, 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('description', 1), ('year', 0)]], {})})),
                ('founders_heading', wagtail.fields.RichTextField(max_length=255, verbose_name='Heading')),
                ('founders_sub_heading', wagtail.fields.RichTextField(max_length=255, verbose_name='Heading')),
                ('founders_description', models.TextField(max_length=2000, verbose_name='Description')),
                ('brand_heading', wagtail.fields.RichTextField(max_length=255, verbose_name='Heading')),
                ('brand_description', models.TextField(max_length=2000, verbose_name='Description')),
                ('brand_image', wagtail.fields.StreamField([('image', 0)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {})})),
                ('article_heading', wagtail.fields.RichTextField(max_length=255, verbose_name='Heading')),
                ('article_description', models.TextField(max_length=2000, verbose_name='Description')),
                ('articles', wagtail.fields.StreamField([('article', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 1: ('wagtail.blocks.URLBlock', (), {'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.DateBlock', (), {'required': True}), 4: ('wagtail.blocks.StructBlock', [[('heading', 0), ('url', 1), ('image', 2), ('publisher', 0), ('date', 3)]], {})}, null=True)),
                ('evolution_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
                ('founder_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading', wagtail.fields.RichTextField(max_length=255, verbose_name='Heading')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('student_works', wagtail.fields.StreamField([('work', 2)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 25, 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('role', 0), ('type', 0), ('profile', 1), ('work', 1)]], {})})),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Alumni',
                'verbose_name_plural': 'Alumni',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading', wagtail.fields.RichTextField(max_length=255, verbose_name='Heading')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('course_url', models.URLField(max_length=255, verbose_name='Course URL')),
                ('course_stating_date', models.DateField(verbose_name='Course Stating Date')),
                ('course_type', models.CharField(max_length=255, verbose_name='Course Type')),
                ('course_rating', models.CharField(max_length=255, verbose_name='Course Rating')),
                ('course_level', models.CharField(max_length=255, verbose_name='Course Level')),
                ('course_duration', models.CharField(max_length=255, verbose_name='Course Duration')),
                ('points', wagtail.fields.StreamField([('point', 0)], block_lookup={0: ('wagtail.blocks.TextBlock', (), {})})),
                ('brand_images', wagtail.fields.StreamField([('image', 0)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {})})),
                ('from_heading', wagtail.fields.RichTextField(max_length=255, verbose_name='Heading')),
                ('key_highlight', wagtail.fields.StreamField([('work', 3)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 25, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('description', 1), ('icon', 2)]], {})})),
                ('certificate_heading', wagtail.fields.RichTextField(max_length=255, verbose_name='Heading')),
                ('certificate_description', models.TextField(max_length=2000, verbose_name='Description')),
                ('certificate_icons', wagtail.fields.StreamField([('icon', 0)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {})})),
                ('mentor_name', models.CharField(max_length=255, verbose_name='Mentor')),
                ('mentor_description', models.TextField(max_length=2000, verbose_name='Description')),
                ('mentor_instagram', models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram URL')),
                ('mentor_linkedin', models.URLField(blank=True, max_length=255, null=True, verbose_name='Linkedin URL')),
                ('breakdown_heading', wagtail.fields.RichTextField(max_length=255, verbose_name='Heading')),
                ('breakdown_description', models.TextField(max_length=2000, verbose_name='Description')),
                ('breakdown_images', wagtail.fields.StreamField([('image', 0)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {})})),
                ('breakdown_points', wagtail.fields.StreamField([('point', 3)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'max_length': 2000, 'required': True}), 2: ('wagtail.blocks.ListBlock', (0,), {'label': 'List of Points'}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('description', 1), ('points', 2)]], {})})),
                ('testimonial_heading', wagtail.fields.RichTextField(max_length=255, verbose_name='Heading')),
                ('testimonials', wagtail.fields.StreamField([('testimonial', 4)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 25, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 3: ('wagtail.blocks.TextBlock', (), {'max_length': 2000, 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('profile', 0), ('name', 1), ('role', 2), ('content', 3), ('logo', 0)]], {})})),
                ('faqs', wagtail.fields.StreamField([('faq', 1)], block_lookup={0: ('wagtail.blocks.TextBlock', (), {'required': True}), 1: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 0)]], {})})),
                ('certificate_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
                ('key_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
                ('mentor_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Course Details',
                'verbose_name_plural': 'Course Details',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CourseListing',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading', wagtail.fields.RichTextField(max_length=255, verbose_name='Heading')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Course Listing',
                'verbose_name_plural': 'Course Listing',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading', wagtail.fields.RichTextField(max_length=255, verbose_name='Heading')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('Brand_images', wagtail.fields.StreamField([('image', 0)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {})})),
                ('who_are_we_heading', wagtail.fields.RichTextField(max_length=255, verbose_name='Heading')),
                ('who_are_we_description', wagtail.fields.RichTextField(max_length=255, verbose_name='Description')),
                ('who_are_we_subheading', models.TextField(max_length=255, verbose_name='Subheading')),
                ('who_are_we_sub_description', models.TextField(max_length=2000, verbose_name='Sub Description')),
                ('who_are_we_images', wagtail.fields.StreamField([('image', 0)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {})})),
                ('who_are_we_points', wagtail.fields.StreamField([('point', 2)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('value', 0), ('image', 1)]], {})})),
                ('commit_heading', wagtail.fields.RichTextField(max_length=255, verbose_name='Heading')),
                ('commit_cards', wagtail.fields.StreamField([('card', 3)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'max_length': 2000, 'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('description', 1), ('image', 2)]], {})})),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='WorkshopDetail',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading', wagtail.fields.RichTextField(max_length=255, verbose_name='Heading')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('course_mentor', models.CharField(max_length=255, verbose_name='Mentor Name')),
                ('course_url', models.URLField(max_length=255, verbose_name='Course URL')),
                ('course_stating_date', models.DateField(verbose_name='Course Stating Date')),
                ('course_type', models.CharField(max_length=255, verbose_name='Course Type')),
                ('course_rating', models.CharField(max_length=255, verbose_name='Course Rating')),
                ('course_level', models.CharField(max_length=255, verbose_name='Course Level')),
                ('course_duration', models.CharField(max_length=255, verbose_name='Course Duration')),
                ('info_heading', wagtail.fields.RichTextField(max_length=255, verbose_name='Heading')),
                ('info_description', models.TextField(max_length=2000, verbose_name='Description')),
                ('info_sub_value', wagtail.fields.StreamField([('value', 2)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 25, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('value', 1)]], {})})),
                ('from_heading', wagtail.fields.RichTextField(max_length=255, verbose_name='Heading')),
                ('key_highlight', wagtail.fields.StreamField([('work', 3)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 25, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('description', 1), ('icon', 2)]], {})})),
                ('galley_heading', wagtail.fields.RichTextField(max_length=255, verbose_name='Heading')),
                ('galley_images', wagtail.fields.StreamField([('image', 0)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {})})),
                ('reviews_heading', wagtail.fields.RichTextField(max_length=255, verbose_name='Heading')),
                ('testimonials', wagtail.fields.StreamField([('testimonial', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 25, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 3: ('wagtail.blocks.TextBlock', (), {'max_length': 2000, 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('profile', 0), ('name', 1), ('role', 2), ('content', 3), ('logo', 0)]], {})}, null=True)),
                ('course_mentor_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
                ('info_main_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
                ('info_sub_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Workshop Detail',
                'verbose_name_plural': 'Workshop Details',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='workshopListing',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading', wagtail.fields.RichTextField(max_length=255, verbose_name='Heading')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Workshop Listing',
                'verbose_name_plural': 'Workshop Listing',
            },
            bases=('wagtailcore.page',),
        ),
    ]
