# Generated by Django 5.1.10 on 2025-06-14 13:18

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselisting',
            name='galley_heading',
            field=wagtail.fields.RichTextField(default='Heading', max_length=255, verbose_name='Heading'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courselisting',
            name='galley_images',
            field=wagtail.fields.StreamField([('image', 0)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, default=[]),
            preserve_default=False,
        ),
    ]
