# Generated by Django 5.1.10 on 2025-06-14 16:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_courselisting_galley_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='who_are_we_heading',
            field=wagtail.fields.RichTextField(default='Heading', max_length=255, verbose_name='Heading'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='who_are_we_images',
            field=wagtail.fields.StreamField([('image', 0)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='who_are_we_points',
            field=wagtail.fields.StreamField([('point', 2)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('value', 0), ('image', 1)]], {})}, default=[]),
            preserve_default=False,
        ),
    ]
